### ISSUE TITLE
Cannot get Reactor.Template

### ISSUE THREAD

**Issue by DerNoobYT** [NuclearPowered/Reactor#10]
If I do what in the logs is written, I'm getting this error by executing the command `dotnet new reactor -n {{ToManyRoles}}`

`Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
Template name "Reactor.Template" (reactor) from author "NuclearPowered" in pack Reactor.Template
    To use this template, run the following command and try again:
        dotnet new -i Reactor.Template::1.0.2`

Then when I do `dotnet new -i Reactor.Template::1.0.2` this error occures (I'm sorry that the error is in german):

`Wiederherzustellende Projekte werden ermittelt...
C:\Program Files\dotnet\sdk\5.0.103\Microsoft.Common.CurrentVersion.targets(93,5): error MSB4184: Der Ausdruck "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 7.0)" kann nicht ausgewertet werden. Could not find a part of the path 'C:\Program Files (x86)\Microsoft SDKs'. [C:\Users\leand\.templateengine\dotnetcli\v5.0.103\scratch\restore.csproj]`

After that the Folder is still empty and I don't know what to do

**Comment by Taahh** [comment]
Make sure you have a .NET SDK installed - https://dotnet.microsoft.com/download/dotnet/5.0 as it says at the top of the page on the documentation @ https://docs.reactor.gg/docs/basic/install_netsdk_example_template

The command to install Reactor is `dotnet new --install Reactor.Template`

**Comment by DerNoobYT** [comment]
It works now! Thanks
