### ISSUE TITLE
Where do i download

### ISSUE THREAD

**Issue by WettleTheDev** [NuclearPowered/Reactor#14]
Hey! I want to make a mod and i am wondering where to download, ty!

**Comment by Cloudy71** [comment]
Good that you wanna make a mod, but in this case, you should learn how to search for things... Reactor dll is in Actions, as it is built automatically. Check reactor's docs for step-by-step tutorial on how to run reactor.

**Comment by MatadorProBr** [comment]
https://docs.reactor.gg/docs/ pog

**Comment by WettleTheDev** [comment]
How do i even download the dotnet?

**Comment by Cloudy71** [comment]
On internet.

**Comment by ToastyBoi1307** [comment]
You need to get a pair of eyes
![image](https://user-images.githubusercontent.com/70444445/112715314-7413df80-8f05-11eb-98b3-10013f3e78c4.png)
