### ISSUE TITLE
Self-Explanatory

### ISSUE THREAD

**Issue by jellytoaster** [NuclearPowered/Reactor#17]
![image](https://user-images.githubusercontent.com/64805926/112688961-ffcb3480-8e4f-11eb-9d3d-ea2fd36f00f5.png)

i have reinstalled bepinex and reactor
started among us with bepinex

version is 12.9 + .net is 5.0

**Comment by DaemonBeast** [comment]
Probably linked to #16

**Comment by jellytoaster** [comment]
i don't really think that's the issue. before when i used visual studio for making among us mods it was working fine

**Comment by js6pak** [comment]
Just follow the docs, and post `dotnet build` output if it still fails

**Comment by js6pak** [comment]
Closing as stale, you can join https://reactor.gg/discord if you are still having problems
