### ISSUE TITLE
Where is the .csproj file in visual studio code

### ISSUE THREAD

**Issue by WettleTheDev** [NuclearPowered/Reactor#19]
Where do i find the .csproj in VS code?

**Comment by DaemonBeast** [comment]
@WettleTheDev Visual Studio Code isn't a C# IDE. You're probably looking for Visual Studio ([download Visual Studio Community 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16)).

**Comment by WettleTheDev** [comment]
Thanks Alot!

**Comment by Cloudy71** [comment]
DO NOT create useless issues which could be solved just by searching on Google. Also, CLOSE your issues when solved.
