### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by angxlwtf** [NuclearPowered/Reactor#2]
Please upload a release as I am having issues building, thank you. 👍

**Comment by XtraCube** [comment]
You need to use CI: **[https://github.com/NuclearPowered/Reactor/actions](https://github.com/NuclearPowered/Reactor/actions)**

**Comment by js6pak** [comment]
You can download CI artifacts from https://github.com/NuclearPowered/Reactor/actions, I'll make release once its releasable
