### ISSUE TITLE
Error :Unhollower

### ISSUE THREAD

**Issue by NotGamerPro** [NuclearPowered/Reactor#26]
[Error  :Unhollower] Exception while unhollowing: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine.CoreModule, Version=3.7.1.6, Culture=neutral, PublicKeyToken=null'

Can you please say why I got this error?

Thank you

**Comment by DaemonBeast** [comment]
You probably don't have Reactor set up properly. Make sure the Reactor version text appears in the top left of the screen when you start the game. Make sure you also have the Reactor NuGet package installed.

**Comment by NotGamerPro** [comment]
Sometimes it doesn't appear in the top left. What should I do for that?

**Comment by DaemonBeast** [comment]
Are you sure you have the latest versions of BepInEx and the Reactor?

**Comment by NotGamerPro** [comment]
I think yes. What are the latest versions of Among Us, Reactor, BeplnEx?

**Comment by DaemonBeast** [comment]
Among Us - 2021.3.31.3s
Reactor - https://github.com/NuclearPowered/Reactor/actions/runs/730803898
BepInEx - https://github.com/NuclearPowered/BepInEx/releases/tag/6.0.0-reactor.18%2Bstructfix

**Comment by NotGamerPro** [comment]
Oh...  My Among Us version is 2021.3.31s. Where can I find reactor.dll for that version?

**Comment by DaemonBeast** [comment]
You should probably just update Among Us.

**Comment by NotGamerPro** [comment]
Ok. Thank you very much.
