### ISSUE TITLE
don't have the Assembly-CSharp-Deobfuscated

### ISSUE THREAD

**Issue by fatalterreur** [NuclearPowered/Reactor#28]
Hello, i have an problem with Reactor 2021.4.12, i don't have the Assembly-CSharp-Deobfuscated in Roaming.reactor\2021.4.12s, why ?

**Comment by zachariapopcorn** [comment]
It could be an error on your end, as I have it for myself

Here's the DLL file if you need it

[Assembly-CSharp-Deobfuscated.zip](https://github.com/NuclearPowered/Reactor/files/6339084/Assembly-CSharp-Deobfuscated.zip)

**Comment by js6pak** [comment]
Please use https://reactor.gg/discord for support
