### ISSUE TITLE
FixedUpdate error

### ISSUE THREAD

**Issue by Thijssie3031** [NuclearPowered/Reactor#31]
So I copied your template, but what I got rn is an error that says:
![image](https://user-images.githubusercontent.com/43790520/115845093-cc64d100-a420-11eb-9e05-bda461eb5dc7.png)
My code:
```cs

using BepInEx;
using BepInEx.Configuration;
using BepInEx.IL2CPP;
using HarmonyLib;
using Reactor;

namespace Reactor.Template
{
    [BepInPlugin(Id)]
    [BepInProcess("Among Us.exe")]
    [BepInDependency(ReactorPlugin.Id)]
    public class TemplatePlugin : BasePlugin
    {
        public const string Id = "me.amogus.mod";

        public Harmony Harmony { get; } = new Harmony(Id);

        public ConfigEntry<string> Name { get; private set; }

        public override void Load()
        {
            Name = Config.Bind("Amogus", "Mod", ":>");

            Harmony.PatchAll();
        }

        [HarmonyPatch(typeof(PlayerControl), nameof(PlayerControl.FixedUpdate))]
        public static class UpdatePatch
        {
            public static void Postfix(PlayerControl __instance)
            {
                __instance.nameText.Text = PluginSingleton<TemplatePlugin>.Instance.Name.Value;
            }
        }
    }
```

**Comment by DaemonBeast** [comment]
Ensure you have the Reactor.OxygenFilter NuGet package installed and follow one of the solutions at https://github.com/NuclearPowered/Reactor/issues/29#issuecomment-822761268.

**Comment by Thijssie3031** [comment]
Yeah and now I got this:
`
reactor.oxygenfilter.msbuild\0.3.0\build\Reactor.OxygenFilter.MSBuild.props(33,9): error MSB4018: The "LoadMappings" task failed unexpectedly.

 System.Net.Http.HttpRequestException: Response status code does not indicate success:
`

All under the error: MSB4018

**Comment by DaemonBeast** [comment]
@Thijssie3031 Try restarting your IDE. If that doesn't help, please send the contents of your `.csproj` file.

**Comment by js6pak** [comment]
Please use https://reactor.gg/discord for support

**Comment by Thijssie3031** [comment]
> Please use https://reactor.gg/discord for support

Can't, I am banned by Chris

**Comment by Thijssie3031** [comment]
> @Thijssie3031 Try restarting your IDE. If that doesn't help, please send the contents of your `.csproj` file.

Want to do that in discord?

**Comment by DaemonBeast** [comment]
@Thijssie3031 But you're banned, so how? Just do it here.

**Comment by Thijssie3031** [comment]
> @Thijssie3031 But you're banned, so how? Just do it here.

Thinking about bringing my discord here but ok. 

```cs
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Version>1.0.0</Version>
        <Mappings>XtraCube/Mappings:0.4.1</Mappings>

        <Description>Mod template for Reactor</Description>
        <Authors>js6pak</Authors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GamePlatform)' == 'Steam'">
        <GameVersion>2021.4.12s</GameVersion>
        <DefineConstants>$(DefineConstants);STEAM</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GamePlatform)' == 'Itch'">
        <GameVersion>2021.4.12s</GameVersion>
        <DefineConstants>$(DefineConstants);ITCH</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <Deobfuscate Include="$(AmongUs)\BepInEx\plugins\Reactor-$(GameVersion).dll" />
        <None Include="..\.editorconfig" Link=".editorconfig" />

        <PackageReference Include="Reactor.OxygenFilter.MSBuild" Version="0.3.0" />
    </ItemGroup>

    <Target Name="Copy" AfterTargets="Reobfuscate">
        <Copy SourceFiles="$(OutputPath)reobfuscated/$(AssemblyName)-$(GameVersion).dll" DestinationFolder="C:\Users\Thijs\Desktop\My own mod\BepInEx\Plugins" Condition="'$(Configuration)' == 'Debug'" />
    </Target>
</Project>
```

**Comment by DaemonBeast** [comment]
@Thijssie3031 You forgot to change the game version to `2021.4.14s` (also, it should be `2021.4.14i` for Itch, but you're not compiling for Itch so it won't actually do anything). Make sure the Reactor dll in your plugins folder has the name `Reactor-2021.4.14s` then run `dotnet build` in a cmd/terminal and if all goes well, restart your IDE to clear out any caching.

**Comment by Thijssie3031** [comment]
.nuget\packages\reactor.oxygenfilter.msbuild\0.3.0\build\Reactor.OxygenFilter.MSBuild.props(37,9): error MSB4018: The "GenerateReferences" task failed unexpectedly.

**Comment by Thijssie3031** [comment]
And btw still the error: MSB4018

**Comment by przebor** [comment]
> > @Thijssie3031 You forgot to change the game version to `2021.4.14s` (also, it should be `2021.4.14i` for Itch, but you're not compiling for Itch so it doesn't actually matter). Make sure the Reactor dll in your plugins folder has the name `Reactor-2021.4.14s` then run `dotnet build` in a cmd/terminal and if all goes well, restart your IDE to clear out any caching.
> > **Edit:** it looks like you tried to merge the two solutions together. It will break; don't do that.
> 
> TBH I had no clue what I was doing here

Then don't do it.
If you don't have any programming (C# in particular) experience, don't even try to touch modding. 
You clearly just send us the error, we say how to fix them and you do whatever we say.

**Comment by DaemonBeast** [comment]
> > @Thijssie3031 You forgot to change the game version to `2021.4.14s` (also, it should be `2021.4.14i` for Itch, but you're not compiling for Itch so it doesn't actually matter). Make sure the Reactor dll in your plugins folder has the name `Reactor-2021.4.14s` then run `dotnet build` in a cmd/terminal and if all goes well, restart your IDE to clear out any caching.
> > **Edit:** it looks like you tried to merge the two solutions together. It will break; don't do that.
> 
> TBH I had no clue what I was doing here

Just follow the top solution (mappings solution) in the guide I sent before.

**Comment by Thijssie3031** [comment]
> > > @Thijssie3031 You forgot to change the game version to `2021.4.14s` (also, it should be `2021.4.14i` for Itch, but you're not compiling for Itch so it doesn't actually matter). Make sure the Reactor dll in your plugins folder has the name `Reactor-2021.4.14s` then run `dotnet build` in a cmd/terminal and if all goes well, restart your IDE to clear out any caching.
> > > **Edit:** it looks like you tried to merge the two solutions together. It will break; don't do that.
> > 
> > 
> > TBH I had no clue what I was doing here
> 
> Then don't do it.
> If you don't have any programming (C# in particular) experience, don't even try to touch modding.
> You clearly just send us the error, we say how to fix them and you do whatever we say.

I do. Cuz I want to learn, instead of being annoying. Try to be helpfull. And that is what you do after someone helps you. you follow the steps xD.

**Comment by Thijssie3031** [comment]
> > > @Thijssie3031 You forgot to change the game version to `2021.4.14s` (also, it should be `2021.4.14i` for Itch, but you're not compiling for Itch so it doesn't actually matter). Make sure the Reactor dll in your plugins folder has the name `Reactor-2021.4.14s` then run `dotnet build` in a cmd/terminal and if all goes well, restart your IDE to clear out any caching.
> > > **Edit:** it looks like you tried to merge the two solutions together. It will break; don't do that.
> > 
> > 
> > TBH I had no clue what I was doing here
> 
> Just follow the top solution (mappings solution) in the guide I sent before ([#29 (comment)](https://github.com/NuclearPowered/Reactor/issues/29#issuecomment-822761268)).

So you're saying you have no other clue of fixing it.

**Comment by DaemonBeast** [comment]
@Thijssie3031 Im saying you didn't follow the guide correctly. Those solutions do work as far as I know.

**Comment by Thijssie3031** [comment]
> Reactor.OxygenFilter NuGet package

Btw how do I even install this

**Comment by Thijssie3031** [comment]
Nvm got it

**Comment by DaemonBeast** [comment]
@Thijssie3031 It looks like the mappings have been updated. You should be able to compile for v2021.4.14s as normal. No need to follow one of the solutions.

**Comment by Thijssie3031** [comment]
MSB4018: The "LoadMappings" task failed unexpectedly

![image](https://user-images.githubusercontent.com/43790520/116424145-8f924300-a841-11eb-8f82-fae504cf4f22.png)

**Comment by DaemonBeast** [comment]
@Thijssie3031 Just set the mappings to `NuclearPowered/Mappings:0.4.0`, the game version to `2021.4.14s` and ensure the Reactor file in your the `BepInEx/plugins` folder in your Among Us directory is called `Reactor-2021.4.14s`.

**Comment by Thijssie3031** [comment]
```cs
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Version>1.0.0</Version>
        <Mappings>NuclearPowered/Mappings:0.4.0</Mappings>

        <Description>Mod template for Reactor</Description>
        <Authors>js6pak</Authors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GamePlatform)' == 'Steam'">
        <GameVersion>2021.4.14s</GameVersion>
        <DefineConstants>$(DefineConstants);STEAM</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GamePlatform)' == 'Itch'">
        <GameVersion>2021.4.14i</GameVersion>
        <DefineConstants>$(DefineConstants);ITCH</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <Deobfuscate Include="$(AmongUs)\BepInEx\plugins\Reactor-$(GameVersion).dll" />
        <None Include="..\.editorconfig" Link=".editorconfig" />

		<PackageReference Include="Reactor.OxygenFilter.MSBuild" Version="0.3.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
    </ItemGroup>

    <Target Name="Copy" AfterTargets="Reobfuscate">
        <Copy SourceFiles="$(OutputPath)reobfuscated/$(AssemblyName)-$(GameVersion).dll" DestinationFolder="C:\Users\x\Desktop\My own mod\BepInEx\Plugins" Condition="'$(Configuration)' == 'Debug'" />
    </Target>
</Project>

```
Starting to think it could be the wrong version of the .NETstandard. But I could be wrong.
Same error

**Comment by DaemonBeast** [comment]
@Thijssie3031 Did you make sure you restart your IDE? If that doesn't work, try running `dotnet build` in a cmd in the solution's directory.

**Comment by Thijssie3031** [comment]
I tried restarting my IDE, even with Visual Studio Restart, but it didn't work. I tried looking on youtube but it also didn't work. Couldn't find the 'Command Palette'

**Comment by Thijssie3031** [comment]
Also CTRL + SHIFT + P didn't work.

**Comment by DaemonBeast** [comment]
@Thijssie3031 Make sure you have the newest version of Reactor. Also, are you still experiencing the same error or a different error?

**Comment by Thijssie3031** [comment]
> @Thijssie3031 Make sure you have the newest version of Reactor. Also, are you still experiencing the same error or a different error?

Well different descriptions of the errors but still all under MSB4018.
And I am quite certain I have the newest version of Reactor:
![image](https://user-images.githubusercontent.com/43790520/116613447-f6deee80-a938-11eb-9f19-d953d7730118.png)

**Comment by DaemonBeast** [comment]
@Thijssie3031 Is the error something like `Generate references failed` or `Load mappings failed`? If not, please send the error with the full description.

**Comment by Thijssie3031** [comment]
Yeah, generate references failed. Some with:  Field HBGEFMAKJCI was not found in EOSManager!

**Comment by DaemonBeast** [comment]
@Thijssie3031 Have you tried setting your mappings to `NuclearPowered/Mappings:0.4.0` and game version to `2021.4.14s` then running `dotnet build` in a cmd/terminal in the solution/project's directory.

**Comment by przebor** [comment]
First of all - why are you trying to patch `EOSManager`?
Second of all - as far as I'm aware, mappings are incomplete for this class (`EOSManager`) as Forte didn't share them in official mappings

**Comment by Thijssie3031** [comment]
> First of all - why are you trying to patch `EOSManager`?
> Second of all - as far as I'm aware, mappings are incomplete for this class (`EOSManager`) as Forte didn't share them in official mappings

Dude, 1. Idk, 2. I get that error when I dotnet build it.

**Comment by Thijssie3031** [comment]
> @Thijssie3031 Have you tried setting your mappings to `NuclearPowered/Mappings:0.4.0` and game version to `2021.4.14s` then running `dotnet build` in a cmd/terminal in the solution/project's directory?
> 
> That `dotnet build` part is really important.

I already did all of that. I did it in the map there, so idk why it gives me an error.

**Comment by Thijssie3031** [comment]
> @Thijssie3031 Does your `AmongUs` environment variable point to your v2021.4.14s install? Also, maybe try setting up the [template mod](https://github.com/NuclearPowered/Reactor.Template) to see if that compiles.

Then I would have to move my whole project... that is not efficient but I will keep that as a last solution. I putted my Among Us variable into the folder: My own mod, where I got Among Us depot downloaded.

**Comment by DaemonBeast** [comment]
@Thijssie3031 Put your Among Us variable into the folder? I'm not sure what you're talking about. Also, are you trying to compile for v2021.4.12s instead of v2021.4.14s?

**Comment by Thijssie3031** [comment]
> @Thijssie3031 Put your Among Us variable into the folder? I'm not sure what you're talking about. Also, are you trying to compile for v2021.4.12s instead of v2021.4.14s?

Well, where the mod is being saved as a .dll/plugin. I do it in a seperate file.

**Comment by Thijssie3031** [comment]
Alright got it fixed. I found the fix. Thanks for your help
