### ISSUE TITLE
Mod No Longer Gets Copied After Getting Built

### ISSUE THREAD

**Issue by viper2kx** [NuclearPowered/Reactor#36]
I hope I am in the correct place.
In the section [Compile the Example mod](https://docs.reactor.gg/quick_start/compile_example_mod) it says run `dotnet build` to compile that succeeds. The notice after it says that it will get copied to the proper folder `BepInEx/plugins`. It doesn't get copied over. It use to, not anymore.

I manually did copy it into the folder.

Here is what I have set up
![image](https://user-images.githubusercontent.com/8532498/123520819-57a85000-d678-11eb-8296-f5de00f98f59.png)

**Comment by DorCoMaNdO** [comment]
`AmongUs` environment variable needs to be set and the build configuration should be `Debug`

**Comment by viper2kx** [comment]
I have the Environment Variable set, and correctly. There are no errors.
I've done all of this a month ago, exactly the same steps as I did today. The mod dll moved into the game then, not moving now.

**Comment by viper2kx** [comment]
I don't mind manually moving it, I just found it odd it didn't automatically do it with the new version of Reactor.

**Comment by DorCoMaNdO** [comment]
`dotnet build -c Debug`

**Comment by viper2kx** [comment]
It still doesn't.

Showing the path to the mod
![image](https://user-images.githubusercontent.com/8532498/123530176-243be480-d6bd-11eb-855e-8ee341b91bc6.png)

Environment Variables
![image](https://user-images.githubusercontent.com/8532498/123530184-4897c100-d6bd-11eb-92e3-11471c1bb884.png)

Command Prompt
![image](https://user-images.githubusercontent.com/8532498/123530199-69601680-d6bd-11eb-87e9-63e10655d763.png)

The File Explorer screenshot is taken after running the command, multiple times.

**Comment by DorCoMaNdO** [comment]
That's not the example project, don't know what you did to your project file but you need this target block https://github.com/NuclearPowered/Reactor/blob/master/AmongUs.props#L20

**Comment by viper2kx** [comment]
There we go. That did it, thank you.
