### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by cootshk** [NuclearPowered/Reactor#39]
When trying to launch mods, I get "[Error  :   BepInEx] Error loading [Reactor 1.0.0-ci.83] : Exception has been thrown by the target of an invocation."

**Comment by DaemonBeast** [comment]
You're probably using an outdated version of NuclearPowered/BepInEx. Try downloading the latest release on the [releases page](https://github.com/NuclearPowered/BepInEx/releases).
