### ISSUE TITLE
Cant join games.

### ISSUE THREAD

**Issue by StackoverflowEnjoyer** [NuclearPowered/Reactor#43]
I used the default template.
When I try to join a game it just shows a black screen.

**Comment by DaemonBeast** [comment]
@StackoverflowEnjoyer Are you making your own mod and using the following template?
https://github.com/NuclearPowered/Reactor.Template

**Comment by StackoverflowEnjoyer** [comment]
@DaemonBeast I am (used docs.reactor.gg), after I put the reactor.dll into /plugins it didnt change anything

**Comment by DaemonBeast** [comment]
Are you using the latest BepInEx? Get the latest il2cpp x86 build here: https://builds.bepis.io/projects/bepinex_be.

**Comment by StackoverflowEnjoyer** [comment]
@DaemonBeast I changed it to the latest BepInEx, it can join games. For some reason it still doesn't show the Reactor version the BepInEx version and the amount of mods, maybe it's because of the new update, but thanks

**Comment by DaemonBeast** [comment]
@StackoverflowEnjoyer Are you sure you're using the latest reactor? Did BepInEx generate the necessary files? Are there any preloader logs or errors in your **LogOutput.txt** file?

**Comment by StackoverflowEnjoyer** [comment]
@DaemonBeast the only warning/error was "Skipping type [pluginname.TemplatePlugin] because its version is invalid."

**Comment by StackoverflowEnjoyer** [comment]
@DaemonBeast the only warning/error was "Skipping type [pluginname.TemplatePlugin] because its version is invalid."
and some preloader logs:

`[Message: Preloader] BepInEx 6.0.0-be.520 - Among Us
[Message: Preloader] BLEEDING EDGE Build #520 from e66c15bdcb82da29bdfc92f7c62a70d655e3a920 at master
[Info : Preloader] Running under Unity v2020.3.7
[Info : Preloader] 0 patcher plugins loaded
[Info : Preloader] 0 assemblies discovered`

And I checked my .csproj and changed it to:
`    <PropertyGroup>
    	<GamePlatform>Steam</GamePlatform>
    <GameVersion>2021.11.9</GameVersion>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="Reactor" Version="1.0.0-rc.1" />
        
    <PackageReference Include="BepInEx.IL2CPP" Version="6.0.0-be.518" />
    <PackageReference Include="AmongUs.GameLibs.$(GamePlatform)" Version="$(GameVersion)" PrivateAssets="all" />
        
    <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="1.0.1" PrivateAssets="all" />
</ItemGroup>

<Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUs)/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
</Target>`

**Comment by StackoverflowEnjoyer** [comment]
@DaemonBeast It kind of works now, but when I'm editing the code "BepinPlugin" and "PlayerControl" are red underlined
