### ISSUE TITLE
Unable to launch game with Reactor

### ISSUE THREAD

**Issue by StackoverflowEnjoyer** [NuclearPowered/Reactor#44]
When I launch the game I get this error:
`[Error  :   BepInEx] Error loading [Reactor 1.1.0-ci.110] : Exception has been thrown by the target of an invocation.`
[Using this BepInEx version](https://github.com/NuclearPowered/BepInEx/releases/tag/6.0.0-reactor.23)
[Using Reactor.dll from here](https://github.com/NuclearPowered/Reactor/actions/runs/1448366532)

**Comment by amsyarasyiq** [comment]
The Reactor build you are using requires latest [BepInEx bleeding edge](https://github.com/BepInEx/BepInEx) build.

You can get the latest bleeding edge BepInEx builds (il2cpp x86 for Among Us) from here: https://builds.bepis.io/projects/bepinex_be

**Comment by StackoverflowEnjoyer** [comment]
@amsyarasyiq It works now, but for some reason dependencies still have a warning symbol next to them and almost everything is red underlined in .cs file

**Comment by StackoverflowEnjoyer** [comment]
@amsyarasyiq It shows up now, but imports in the reactor tempalte still dont work
