### ISSUE TITLE
Reactor broke (again)

### ISSUE THREAD

**Issue by koxx12-dev** [NuclearPowered/Reactor#49]
log
 ```
 [Error  :    Detour] System.MissingMethodException: Method not found: void Hazel.Udp.UnityUdpClientConnection..ctor(Il2CppSystem.Net.IPEndPoint,Hazel.IPMode)
  at (wrapper dynamic-method) AuthManager.DMD<AuthManager::CreateDtlsConnection>(string,uint16)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) CreateDtlsConnection(intptr,uint16,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
 ```
 
 reason (at least i think so?)
 ```
 Hazel.Udp.UnityUdpClientConnection doesnt have (Il2CppSystem.Net.IPEndPoint,Hazel.IPMode) as a constructor anymore
 instead it now has (Hazel.ILogger logger,Il2CppSystem.Net.IPEndPoint remoteEndPoint,Hazel.IPMode ipMode)
 ```
![dotPeek64 2021 3 1_eWCtMcGeV8](https://user-images.githubusercontent.com/80456351/146649893-f635f304-6713-44e4-9e24-6323fb7fc313.png)

**Comment by yukieiji** [comment]
According to the following commit, fixing [this](https://github.com/NuclearPowered/Reactor/blob/837ee142b366a3599fe21d71666895000a8164c0/Reactor/Patches/CustomServersPatch.cs#L44) seems to fix it
https://github.com/Eisbison/TheOtherRoles/commit/f5f3145d60818c0b709a7401ef2b62f4beae4ce8
