### ISSUE TITLE
Crashing issue 

### ISSUE THREAD

**Issue by angxlwtf** [NuclearPowered/Reactor#50]
Crashes occur on newer versions of BepInEx just by joining a game or joining freeplay. 
Pretty easy to reproduce: download a newer version of BepInEx, it wont crash until you use Reactor which confirms its a Reactor issue. This isn't my problem either, as other people have tried it and had the same problem.

The last working version is 530.

**Comment by angxlwtf** [comment]
I was wrong, it wasnt a Reactor issue.

**Comment by js6pak** [comment]
Fixed by https://github.com/BepInEx/BepInEx/pull/352
