### ISSUE TITLE
Outdated Version Of Amonf Us

### ISSUE THREAD

**Issue by toivocat** [NuclearPowered/Reactor#51]
It is still on version 2021.11.9 when 2021.12.14 is out. Could you update it to that?

**Comment by angxlwtf** [comment]
It is updated.. Use the actions tab, not releases.

**Comment by toivocat** [comment]
Sorry, got it

**Comment by angxlwtf** [comment]
No problem

**Comment by js6pak** [comment]
Use https://github.com/NuclearPowered/Reactor/releases/tag/1.2.0
