### ISSUE TITLE
not working on linux

### ISSUE THREAD

**Issue by Pietrodjaowjao** [NuclearPowered/Reactor#54]
[Error  :   BepInEx] Error loading [Reactor 1.2.3-ci.138] : Exception has been thrown by the target of an invocation.

**Comment by DaemonBeast** [comment]
Are you using the latest il2cpp x86 BepInEx build from here: <https://builds.bepinex.dev/projects/bepinex_be>?

**Comment by Pietrodjaowjao** [comment]
bi

**Comment by Pietrodjaowjao** [comment]
when i put this bepinex version, the game dont opens

**Comment by DaemonBeast** [comment]
Any preloader logs or log outputs?

**Comment by Pietrodjaowjao** [comment]
nevermind, i put 32 bits, the game crashed, then i put 64, dont worked, but when i put 32 bits again worked
