### ISSUE TITLE
Disable timeout as part of reactor?

### ISSUE THREAD

**Issue by danbudworthmead** [NuclearPowered/Reactor#56]
![image](https://user-images.githubusercontent.com/9319945/177800408-761ad496-d497-44f4-8c9f-35c7d3610268.png)

It makes sense, no?

**Comment by Galster-dev** [comment]
In my opinion it either should only be a part of Reactor.Debugger or server-sided. Such things only needed when actively developing and devs just use local game or host their own development server with banning off.

**Comment by danbudworthmead** [comment]
> In my opinion it either should only be a part of Reactor.Debugger or server-sided. Such things only needed when actively developing and devs just use local game or host their own development server with banning off.

Pretty sure it's client side, not server side. Hence why you can get the timeout by hard shutting down a server.
