### ISSUE TITLE
RPC Method Potential Bug

### ISSUE THREAD

**Issue by xxomega77xx** [NuclearPowered/Reactor#61]
I am unsure as to why with the newest update of AU the RPC Methods I had in place now throw a null reference error, I am not getting any inline code errors but the attached log should give some insight.

[LogOutput.log](https://github.com/NuclearPowered/Reactor/files/9440724/LogOutput.log)

**Comment by js6pak** [comment]
The error message probably should be made more clear, but the issue is on your side. 
2022.8.23 added an additional optional parameter to `SoundManager#PlaySound` thus breaking binary compatiblity, make sure you are targeting `2022.8.23` when compiling your mod.

**Comment by xxomega77xx** [comment]
Thanks now I feel stupid compiled correctly and working now ugh
