### ISSUE TITLE
Reactor not loading

### ISSUE THREAD

**Issue by raining-codes** [NuclearPowered/Reactor#70]
In bepinix console, it showes that only one plugin to load and thats my plugin created with Reactor.Template, it doesnt load Reactor.dll and when loading my mod it showes error - Could not load [mymod 1.0.0-dev] because it has missing dependencies: gg.reactor.api

**Comment by js6pak** [comment]
Can you post the full `BepInEx/LogOutput.log` file?

**Comment by raining-codes** [comment]
I have resolved this by downloading newer version of among us and reactor.

Thanks for taking the time to check the issue
